### PR TITLE
exit with nonzero status on error

### PR DESCRIPTION
**Pull request by thenaterhood**
Should address #359, but I'm a little rusty on context.

### CODE REVIEW

**Review by jwflory — APPROVED** [review]
Seems okay to me, and it would definitely be nice for system administrators using systemd to manage the bot as a service.

I suggest one other person to review as well since I am rusty on Go.

**Comment by Tjzabel** [comment]
@thenaterhood This looks good, but how exactly did you test this? I'm having trouble replicating a scenario where TeleIRC returns an exit 0 where it shouldn't.

**Comment by thenaterhood** [comment]
@Tjzabel either start teleirc without any internet connection or configure a totally invalid IRC server (in theory a bad telegram configuration too, but you'll get a nil pointer crash instead). I'm sure there may be others, but I didn't trace to find them.

**Comment by jwflory** [comment]
@Tjzabel Any luck on replicating? I haven't had a chance yet to set up my development environment again after a system reinstall.

**Comment by Tjzabel** [comment]
> @Tjzabel Any luck on replicating? I haven't had a chance yet to set up my development environment again after a system reinstall.

I haven't yet been able to.

**Review by Tjzabel — APPROVED** [review]
Checks out! Thanks :+1:

**Comment by jwflory** [comment]
Seems good to me. All checks are green. Merging! 🏁

**Pull request merged**
