### PR TITLE
Add [EDITED] prefix for edited messages on irc.

### PR DESCRIPTION
**Pull request by Palid**
This pull request adds edited prefix on IRC when the message was edited.

### CODE REVIEW

**Comment by Tjzabel** [comment]
@Palid I've tested this locally off your branch, and everything works! This is definitely something we want to include :+1: 

This may also indirectly give some leeway to issue #41 

The *only* thing I want input on from others is whether or not `[EDIT]` is too strong of a pre-text message.

**Comment by xforever1313** [comment]
I think this is a good first step to get the feature working; the change is simple and should work fine.  [EDIT] is fine in my opinion as a default prefix, especially since it is user configurable.  I don't have a  strong opinion either way though.

I see no reason why we can't merge this in to get this feature up and running.  However, I do have a concern going forward with the changes to TgEventListener.  TgEventListener shouldn't do any message manipulation, it should just determine which event to trigger, and let the TgEventHandlers handle the event.  See my comment in #41 (https://github.com/RITlug/teleirc/issues/41#issuecomment-450276016) for an idea to use this pattern.  That, however, is a lot more work to get up and running correctly, and a task for a different day (probably when we try to fix #41).

The other thing to check before merging is what if someone sets IRC_EDITED_PREFIX in the env file to ```null``` or ```undefined```?  Do we crash?  If not, then I approve this pull.  If it does, then checks should be added to TeleIrc.js's initStage2_telegramConfigValidation().

Thanks for the PR!

**Comment by Tjzabel** [comment]
@xforever1313 makes sense. In terms of setting `IRC_EDITED_PREFIX` to null or undefined, nothing happens. If nothing is there, it just reverts to the default set as `[EDIT] `. 

I've tested this with literal `null, `undefined`, and nothing, in addition to random characters. Everything just gets passed as string literals, or the default otherwise.

**Comment by Tjzabel** [comment]
@xforever1313 Since you think the merge is good to go, I'm going to go ahead and do the merge :+1: 

Feel free to either add a comment to update the previous issue, or open up another issue with your concerns for the future state of `TgEventListener` and `TgEventHandler`.

**Comment by jwflory** [comment]
@Palid Thanks for submitting this feature! :tada:

**Comment by Palid** [comment]
If nobody will refactor it before half of February I'll gladly do it. Unfortunately before that that I'm flooded with work and won't have enough time to properly refactor this.

**Pull request merged**
