### PR TITLE
Fix nil pointer crash if telegram auth fails

### PR DESCRIPTION
**Pull request by thenaterhood**
Random discovery of the evening :)
I'm not sure if there's a timing problem or if in some cases we don't get back an error. I can replicate this by deleting a character off the telegram key I'm using.

Alternatively there's something else entirely going on here and this just masks it.

Before:
```
$ ./teleirc
INFO: 2022/03/29 21:46:58 Current TeleIRC version: v2.2.0-9-g129dcac
INFO: 2022/03/29 21:46:58 Creating new Telegram bot client...
INFO: 2022/03/29 21:46:58 Creating new IRC bot client...
INFO: 2022/03/29 21:46:58 Starting up Telegram bot...
INFO: 2022/03/29 21:46:58 Starting up IRC bot...
ERROR: 2022/03/29 21:47:03 Unauthorized
ERROR: 2022/03/29 21:47:03 Unauthorized
INFO: 2022/03/29 21:47:03 Shutting Down...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x69d3c9]

goroutine 9 [running]:
github.com/ritlug/teleirc/internal/handlers/telegram.(*Client).StartBot(0xc0002c1640, 0x0?, 0xc0002c1680)
        /home/nate/projects/teleirc/internal/handlers/telegram/telegram.go:60 +0x1a9
created by main.main
        /home/nate/projects/teleirc/cmd/teleirc.go:53 +0x5f8
```

After:
```
$ ./teleirc
INFO: 2022/03/29 22:06:29 Current TeleIRC version: v2.2.0-11-g5a08266
INFO: 2022/03/29 22:06:29 Creating new Telegram bot client...
INFO: 2022/03/29 22:06:29 Creating new IRC bot client...
INFO: 2022/03/29 22:06:29 Starting up Telegram bot...
INFO: 2022/03/29 22:06:29 Starting up IRC bot...
ERROR: 2022/03/29 22:06:30 Unauthorized
ERROR: 2022/03/29 22:06:30 Failed to authenticate to Telegram
ERROR: 2022/03/29 22:06:30 Unauthorized
INFO: 2022/03/29 22:06:30 Shutting Down...
INFO: 2022/03/29 22:06:30 Exiting
```

### CODE REVIEW

**Review by jwflory — COMMENTED** [review]
Simple and clean. I like it and it removes ambiguity. I guess the Telegram library panics if an API token doesn't match the expected output.

@thenaterhood Are you willing to write a test for this? CodeClimate fails this PR because it reduces the test coverage by 0.3%. It's not terrible and I'd still be okay to merge, but it would be ideal if we could write a unit test for this change as it goes in. WDYT?

**Comment by thenaterhood** [comment]
I'm not sure how worthwhile it would be to write a test for this because this results from a direct call to an external library that we're not at all set up to be able to mock here. It's not in any way impossible to do, but it would require some restructuring of the code itself and a possibly extensive mock for the whole tgbbot API struct.

**Review by jwflory — APPROVED** [review]

**Review by Tjzabel — APPROVED** [review]

**Comment by Tjzabel** [comment]
I tested the change and it works as intended. We have a separate issue on the backlog for seeing if there's a better way we can go about testing/mocking out the TG library.

**Comment by Tjzabel** [comment]
Since this is a simple, QOL pr i'm going to merge this through.

**Pull request merged**
