### PR TITLE
docs: Add Message State Diagram (closes #221)

### LINKED ISSUE #221: Create state diagram for messages
# Summary

Create a state diagram of how messages should be passed through TeleIRC

# Background

**Is your feature request related to a problem? Please describe**:
We are working on handler implementation and starting to think about how to cleanly structure the application. This is a complex problem and requires us to use some forethought to predict future challenges and use cases of the redesigned TeleIRC.

**Describe the solution you'd like**:
A state diagram is one tool available to help us visualize and understand different states. When we follow the state of something like a message, we can think about all the actions that need to happen on the object and what changes/transitions need to happen.

**Describe alternatives you've considered**:
There are other UML choices, but I think a state diagram is most useful.

# Details

We discussed this in the [2019-11-09 developer meeting](https://bluejeans.com/s/PqBG7/). Together, @Tjzabel whiteboarded this out together. My action item is to make a prettier digital version and add it to our documentation:

Whiteboard draft of a Message state diagram, to understand what changes/permutations are applied to a message as it travels through our codebase

# Outcome

* Shared understanding of what the application architecture should look like
* Common reference and guide when planning future features

### PR DESCRIPTION
**Pull request by jwflory**
Closes #221.

This commit adds a new docs page to our site with a digitized version of
the Message State Diagram we white-boarded a couple weeks back. The goal
of this document is to bring all developers on the same page about how
Messages pass through TeleIRC. While this helps new developers, it also
helps us stay focused by keeping to the expected states and avoiding
deviation.

Screenshot of rendered Message State Diagram page

### CODE REVIEW

**Comment by Tjzabel** [comment]
@jwflory I like it! My only question is merging this documentation into master, where these dev docs don't reflect the current state of TeleIRC, and is therefore misleading until the Go port is complete. 

I see this is specifically under development documentation, so I am overall okay with this PR due to it being helpful for the developers. I just wanted to point that out.

**Comment by jwflory** [comment]
@Tjzabel Let me add a disclaimer about the diagram being for the v2.0 Go port. I'll get to it by Friday.

**Comment by Tjzabel** [comment]
@jwflory reminder to please add a disclaimer this is for the v2.0 Go Port :upside_down_face:

**Comment by jwflory** [comment]
I added the caption and rebased my commits. Here is what the page looks like now:

Updated screenshot of docs page

**Pull request merged**
