### PR TITLE
Add support for IRC server options

### PR DESCRIPTION
**Pull request by gnikandrov**
Well, I hope both the title and the code are pretty selfdescriptive. I wanted to use this bot on RusNet, so I had to select different port, but didn't find an option to do so.
Issue #113 seems to be related.

### CODE REVIEW

**Comment by Tjzabel** [comment]
@gnikandrov thanks for the PR! This is a simple enough change, and everything looks good on my end. TravisCI is failing for some reason on node 10, but I've been unable to replicate the error locally. 

It's not a complete blocker on having this PR go through, but I am going to spend some time figuring out why it's failing.

**Comment by Tjzabel** [comment]
Nice! @jwflory I removed the caching from Travis CI, and that seems to have fixed our issue here.

**Comment by Tjzabel** [comment]
@gnikandrov thanks again for the PR! Merging :+1:

**Comment by jwflory** [comment]
Thanks for submitting this PR @gnikandrov! :tada:

**Pull request merged**
