### PR TITLE
SSL flag

### LINKED ISSUE #329: Connecting to IRC over SSL (Port 6697) does not work
# Summary

TeleIRC is not able to connect to IRC over SSL.

## How to reproduce?
Run TeleIRC over SSL for IRC.

## Expected behavior
TeleIRC is able to properly run over SSL on IRC.

## Stacktrace
```
INFO: 2020/07/24 18:41:14 Current TeleIRC version: v2.0
INFO: 2020/07/24 18:41:14 Creating new Telegram bot client...
INFO: 2020/07/24 18:41:14 Creating new IRC bot client...
INFO: 2020/07/24 18:41:14 Starting up Telegram bot...
INFO: 2020/07/24 18:41:14 Starting up IRC bot...
ERROR: 2020/07/24 18:41:15 read tcp 192.168.1.249:45244->64.86.243.181:6697: read: connection reset by peer
ERROR: 2020/07/24 18:41:15 read tcp 192.168.1.249:45244->64.86.243.181:6697: read: connection reset by peer
```

# Other details
Port `7000` is another port confirmed to not work properly.

### PR DESCRIPTION
**Pull request by thenaterhood**
Fixes #329

### CODE REVIEW

**Review by Tjzabel — APPROVED** [review]
LGTM. This is as low-hanging fruit as it can get :p

**Review by Tjzabel — CHANGES_REQUESTED** [review]
I am actually going to request some changes. Can you please add `IRC_USE_SSL` to the `docs/` as well?

**Review by jwflory — APPROVED** [review]
I tested this out locally. It works :grinning: I am marking my review as approved, but I would also like to add this into our docs like @Tjzabel suggested in his review.

**Comment by thenaterhood** [comment]
Yup, sure can. I'll do that for the other PR I've got open too, no mysterious new options here.

**Review by Tjzabel — APPROVED** [review]
This fix looks a little sus

**Pull request merged**
