### PR TITLE
Changed directory structure to initial Go structure

### PR DESCRIPTION
**Pull request by Zedjones**
Changed the directory structure around as discussed, only thing I wasn't sure of was if we want to deleted the .travis.yml and .codeclimate.yml files or leave them to be changed later.

### CODE REVIEW

**Comment by Tjzabel** [comment]
@Zedjones can you remove the travis-ci file? It's preventing this from going through, since naturally Travis will fail here.

**Comment by Zedjones** [comment]
Removed the requested files

**Comment by Tjzabel** [comment]
Thanks for the changes. Travis is hanging a little bit. If in 10 mins it's still waiting for status to be reported, I'll just manually merge this through, and  make sure it's working as expected after that.

**Comment by Tjzabel** [comment]
I'm going to close this PR and open a new one with a working TravisCI template.

**Pull request closed without merging**
