### PR TITLE
Config test cherrypick

### PR DESCRIPTION
**Pull request by xforever1313**
Repull of #23, since I suck at git and can't handle conflicts :|.

Same changes, different pull.

### CODE REVIEW

**Comment by robbyoconnor** [comment]
why not squash this?

**Comment by thenaterhood** [comment]
I think we have squashes disabled on the repo for some reason, but a squash and merge would be the best approach for this. There's still a conflict here for some reason though that I'm looking into.

**Comment by thenaterhood** [comment]
Github has lied to me, apparently. There is no longer a conflict now that I've refreshed the page. Wut. All good by me though and it's the same changes that were waiting for my approval in #23 so I'm pulling the trigger.

**Comment by robbyoconnor** [comment]
also, I can teach you how to resolve conflicts -- it's not that bad :)

**Pull request merged**
