### PR TITLE
Added a DisconnectHandler that sends a message to Telegram if IRC Dies

### LINKED ISSUE #96: Send Telegram notification when connection to IRC is lost/restored
# Summary

Send notification from Telegram bot to group when IRC connection is lost and when it is restored

# Background

Sometimes the bot may crash, restart, or otherwise not be connected. In IRC, this is clear because the bot has to join the channel and have proper permissions to speak. In Telegram, there is no indication when the connection is broken. It might be helpful to prevent a [situation like this](https://www.youtube.com/watch?v=k0pL_CsK3Dk)…

# Details

I'm not sure what our current options are to get the state of the IRC connection. If it's easy to get, then we should have an event handler for when the connection disconnects and reconnects after the bot's initial start-up.

# Outcome

Less confusion when a connection drops and cross-bridge conversation is interrupted (and messages will never be relayed automatically later)

### PR DESCRIPTION
**Pull request by xforever1313**
Resolves #96

When the IRC Connection's DISCONNECTED event is triggered, the bot will now send a "lost connection" message to the Telegram Channel.  Specifically, the message will be "Lost connection to '<channel>' on '<server>'".  It will only show this message if the "SHOW_DISCONNECT_MESSAGE" setting is set to true.

This was tested by adding a firewall rule on my test PC to block the IRC port, and sure enough, a few seconds later, we get the error message in Telegram.

...
Side-Note: It appears as though if the IRC connection does die, the process also dies.  We get this in the Console:

```
ERROR: 2020/10/11 17:22:02 read tcp 192.168.15.174:56524->195.148.124.79:6697: wsarecv: An established connection was aborted by the software in your host machine.
ERROR: 2020/10/11 17:22:02 read tcp 192.168.15.174:56524->195.148.124.79:6697: wsarecv: An established connection was aborted by the software in your host machine.
```

There is no reconnection logic built into Teleirc other than the thing launching (e.g. systemd) it auto-restarting it, so that's probably fine (if not, may be worth a new issue).

### CODE REVIEW

**Review by Tjzabel — APPROVED** [review]
Checks out for me!

**Review by robbyoconnor — APPROVED** [review]
Looks **_GREAT_** to me!

**Comment by robbyoconnor** [comment]
Shall I merge?

**Comment by robbyoconnor** [comment]
I merged.

**Comment by jwflory** [comment]
This came up in the dev chat, but thought I would put it here for posterity too. If the IRC connection dies, it is OK if the process also dies. This is handled through the systemd unit file we ship upstream to automatically restart the process when it dies. Also, later on, once we revisit containers ( #228 ), k8s or OpenShift can spin up new pods if one connection dies.

**Comment by Tjzabel** [comment]
@xforever1313 actually, can you please add the `IRC_DISCONNECT` option to the config glossary in the docs as well?

**Comment by jwflory** [comment]
Oops, I always forget the docs for changes to the config options :see_no_evil:

**Pull request merged**
