### PR TITLE
Don't forward messages with a configurable prefix

### LINKED ISSUE #201: Feature request: filter messages starting with a prefix
An IRC channel I use for work has a bot set up to log all messages except the ones starting with a specific prefix (`[off]`), for privacy concerns.

Currently, that is stopping us from using TeleIRC, as we don't want those messages logged elsewhere.

A feature to filter outgoing messages that start with a prefix would be greatly appreciated (hopefully not just for our use-case) and fairly easy to implement.

I'm happy to open a PR if you are interested in this feature.

### PR DESCRIPTION
**Pull request by thenaterhood**
Fixes #201

### CODE REVIEW

**Comment by thenaterhood** [comment]
I added this for both sides, since I've seen concern from folks who occasionally don't want their messages leaving Telegram.

**Review by Tjzabel — CHANGES_REQUESTED** [review]
@thenaterhood awesome! Since you added to the config file, can you please add this info into the `docs/` as well?

**Review by Tjzabel — APPROVED** [review]
LGTM

**Comment by jwflory** [comment]
I tested this locally and it works like a charm! I followed @MonkeyDo's use case with the `[off]` prefix:

Screenshot of a conversation over TeleIRC - from the IRC side

Screenshot of a conversation over TeleIRC - from the Telegram side

Going to merge this. :clapper: Thanks @thenaterhood! :raised_hands:

**Pull request merged**
