### PR TITLE
[RDY] Docker improvements

### LINKED ISSUE #24: Docker containers should not operate as root!
Docker containers should whenever possible become a non-privileged user. The root user in the containers has access to **_EVERYTHING_**.  Let me reiterate, root in container means root in the main system.

I plan on fixing this but wanted an issue attached to this.

### PR DESCRIPTION
**Pull request by robbyoconnor**
This PR does various things all centered around Docker improvements -- a lot of security but an addition too!
Changes: 
- Make the teleirc not run as root in the Docker images
- add a dockerignore to not bake in everything.
- Add a table comparing the Docker image sizes for educated decisions
- Nuke config.js.docker in favor of config.js.example
- Add a docker-compose.yml example file and document it in the README
- Add dotenv for reuse of the .env file from docker-compose for running
  natively
- Improvements to the README around configuration
Closes #24

### CODE REVIEW

**Comment by robbyoconnor** [comment]
@jflory7

**Comment by robbyoconnor** [comment]
I'm cleaning things up -- but if you want to review the alpine image is done. I'm cleaning up the ubuntu/fedora ones.

**Comment by robbyoconnor** [comment]
Ready showtime!

**Comment by robbyoconnor** [comment]
Added [dotenv](https://www.npmjs.com/package/dotenv) -- allows us to reuse the `.env` file from docker-compose

**Comment by itamarjp** [comment]
procps-ng - can be removed from fedora, I added it to debug some stuff

@development-tools -> this is a group and its installs alot of packages, its the responsible for Fedora image being the biggest, to make it smaller we need to remove this and add the names of individual packages requited to run teleirc, I did this because I am doing alot of stuff these days and for me theres no difference if image is 500Mb or 1Gb.

**Comment by robbyoconnor** [comment]
@itamarjp -- the biggest problem is that you're running as root...

**Comment by robbyoconnor** [comment]
@itamarjp -- the biggest problem is that you're running as root...Docker containers are single-purpose. You install SOLELY what you need. It's why Alpine Linux is so popular.

**Comment by robbyoconnor** [comment]
I'm gonna leave fixing the fedora image's  size to another PR...let's not block this PR as it's a **_HUGE_** security problem right now.

**Comment by robbyoconnor** [comment]
I'm gonna leave fixing the fedora image's  size to another PR...let's not block this PR as it's fixing a **_HUGE_** security problem right now.

**Pull request merged**
